packages:
  - demos/**
  - frameworks/**
  - packages/**

  # exclude packages that are inside dist/test directories
  - '!**/dist/**'

catalog:
  '@4tw/cypress-drag-drop': ^2.3.0
  '@eslint/js': ^9.36.0
  '@faker-js/faker': ^10.0.0
  '@fnando/sparkline': ^0.3.10
  '@formkit/tempo': ^0.1.2
  '@popperjs/core': ^2.11.8
  '@types/fnando__sparkline': ^0.3.7
  '@types/node': ^24.5.2
  '@types/sortablejs': ^1.15.8
  '@vitejs/plugin-react': ^5.0.3
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/coverage-v8': ^4.0.0-beta.13
  '@vitest/ui': ^4.0.0-beta.13
  bootstrap: ^5.3.8
  cross-env: ^10.0.0
  cypress: ^15.2.0
  cypress-real-events: ^1.15.0
  dequal: ^2.0.3
  dompurify: ^3.2.7
  eslint: ^9.36.0
  eslint-plugin-cypress: ^5.1.1
  eslint-plugin-n: ^17.23.1
  globals: ^16.4.0
  i18next: ^25.5.2
  i18next-vue: ^5.3.0
  jsdom: ^27.0.0
  jsdom-global: ^3.0.2
  multiple-select-vanilla: ^4.3.9
  native-copyfiles: ^1.3.5
  npm-run-all2: ^8.0.4
  remove-glob: ^0.4.0
  rxjs: ^7.8.2
  sass: ^1.93.0
  sortablejs: ^1.15.6
  tslib: ^2.8.1
  typescript: ^5.8.3
  typescript-eslint: ^8.44.0
  vite: npm:rolldown-vite@latest
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.0-beta.13
  vue: ^3.5.21
