packages:
  - demos/**
  - frameworks/**
  - frameworks-plugins/**
  - packages/**
  - '!**/dist/**'

catalog:
  '@4tw/cypress-drag-drop': ^2.3.1
  '@angular-eslint/eslint-plugin': ^20.7.0
  '@faker-js/faker': ^10.2.0
  '@fnando/sparkline': ^0.3.10
  '@formkit/tempo': ^1.0.0
  '@popperjs/core': ^2.11.8
  '@types/fnando__sparkline': ^0.3.7
  '@types/node': ^24.10.9
  '@types/sortablejs': ^1.15.9
  '@vitejs/plugin-react': ^5.1.2
  '@vitejs/plugin-vue': ^6.0.3
  '@vitest/coverage-v8': ^4.0.17
  '@vitest/ui': ^4.0.17
  bootstrap: ^5.3.8
  cross-env: ^10.1.0
  cypress: ^15.9.0
  cypress-real-events: ^1.15.0
  dequal: ^2.0.3
  dompurify: ^3.3.1
  globals: ^17.0.0
  i18next: ^25.7.4
  i18next-vue: ^5.4.0
  jsdom: ^27.4.0
  jsdom-global: ^3.0.2
  multiple-select-vanilla: ^4.4.1
  native-copyfiles: ^1.3.7
  npm-run-all2: ^8.0.4
  oxlint: ^1.41.0
  remove-glob: ^0.4.10
  rxjs: ^7.8.2
  sass: ^1.97.2
  sortablejs: ^1.15.6
  tslib: ^2.8.1
  typescript: ^5.8.3
  vite-tsconfig-paths: ^6.0.4
  vitest: ^4.0.17
  vue: ^3.5.26

# named catalog: to reference multiple version of a dependency
# Can be referenced through "catalog:vite6" or "catalog:vite7"
catalogs:
  vite6:
    vite: ^6.4.1
  vite7:
    vite: ^7.3.1

onlyBuiltDependencies:
  - cypress
