packages:
  - demos/**
  - frameworks/**
  - packages/**

catalog:
  '@4tw/cypress-drag-drop': ^2.3.0
  '@faker-js/faker': ^9.7.0
  '@fnando/sparkline': '^0.3.10'
  '@formkit/tempo': ^0.1.2
  '@popperjs/core': ^2.11.8
  '@types/fnando__sparkline': ^0.3.7
  '@types/node': ^22.15.17
  '@types/sortablejs': ^1.15.8
  '@vitejs/plugin-vue': ^5.2.4
  '@vitest/coverage-v8': ^3.1.3
  '@vitest/ui': ^3.1.3
  bootstrap: ^5.3.6
  cross-env: ^7.0.3
  cypress: ^14.3.3
  cypress-real-events: ^1.14.0
  dequal: ^2.0.3
  dompurify: ^3.2.5
  globals: ^16.1.0
  i18next: ^25.1.2
  i18next-vue: ^5.3.0
  jsdom: ^26.1.0
  multiple-select-vanilla: ^4.1.4
  native-copyfiles: ^0.3.2
  npm-run-all2: ^8.0.1
  rimraf: ^6.0.1
  rxjs: ^7.8.2
  sass: ^1.87.0
  sortablejs: ^1.15.6
  tslib: ^2.8.1
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.1.3
  vue: ^3.5.14
