packages:
  - demos/**
  - frameworks/**
  - packages/**

  # exclude packages that are inside dist/test directories
  - '!**/dist/**'

catalog:
  '@4tw/cypress-drag-drop': ^2.3.0
  '@eslint/js': ^9.31.0
  '@faker-js/faker': ^9.9.0
  '@fnando/sparkline': ^0.3.10
  '@formkit/tempo': ^0.1.2
  '@popperjs/core': ^2.11.8
  '@types/fnando__sparkline': ^0.3.7
  '@types/node': ^22.16.3
  '@types/sortablejs': ^1.15.8
  '@vitejs/plugin-vue': ^6.0.0
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  bootstrap: ^5.3.7
  cross-env: ^7.0.3
  cypress: ^14.5.1
  cypress-real-events: ^1.14.0
  dequal: ^2.0.3
  dompurify: ^3.2.6
  eslint: ^9.31.0
  eslint-plugin-cypress: ^5.1.0
  eslint-plugin-n: ^17.21.0
  globals: ^16.3.0
  i18next: ^25.3.2
  i18next-vue: ^5.3.0
  jsdom: ^26.1.0
  jsdom-global: ^3.0.2
  multiple-select-vanilla: ^4.3.4
  native-copyfiles: ^1.3.4
  npm-run-all2: ^8.0.4
  remove-glob: ^0.3.4
  rxjs: ^7.8.2
  sass: ^1.89.2
  sortablejs: ^1.15.6
  tslib: ^2.8.1
  typescript: ^5.8.3
  typescript-eslint: ^8.36.0
  vite: ^7.0.4
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vue: ^3.5.17
