packages:
  - demos/**
  - frameworks/**
  - packages/**
  - examples/**

catalog:
  '@4tw/cypress-drag-drop': ^2.3.0
  '@faker-js/faker': ^9.4.0
  '@fnando/sparkline': '^0.3.10'
  '@formkit/tempo': ^0.1.2
  '@types/fnando__sparkline': ^0.3.7
  '@types/node': ^22.13.1
  '@types/sortablejs': ^1.15.8
  cross-env: ^7.0.3
  cypress: ^14.0.1
  cypress-real-events: ^1.14.0
  dequal: ^2.0.3
  dompurify: ^3.2.4
  multiple-select-vanilla: ^3.4.4
  npm-run-all2: ^7.0.2
  rxjs: ^7.8.1
  sass: ^1.83.4
  sortablejs: ^1.15.6
  typescript: ^5.7.3
  vite: ^6.0.11
  whatwg-fetch: ^3.6.20
