packages:
  - demos/**
  - frameworks/**
  - packages/**
  - '!**/dist/**'

catalog:
  '@4tw/cypress-drag-drop': ^2.3.1
  '@faker-js/faker': ^10.1.0
  '@fnando/sparkline': ^0.3.10
  '@formkit/tempo': ^0.1.2
  '@popperjs/core': ^2.11.8
  '@types/fnando__sparkline': ^0.3.7
  '@types/node': ^24.10.0
  '@types/sortablejs': ^1.15.9
  '@vitejs/plugin-react': ^5.1.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/coverage-v8': ^4.0.6
  '@vitest/ui': ^4.0.6
  bootstrap: ^5.3.8
  cross-env: ^10.1.0
  cypress: ^15.5.0
  cypress-real-events: ^1.15.0
  dequal: ^2.0.3
  dompurify: ^3.3.0
  globals: ^16.5.0
  i18next: ^25.6.0
  i18next-vue: ^5.3.0
  jsdom: ^27.1.0
  jsdom-global: ^3.0.2
  multiple-select-vanilla: ^4.4.0
  native-copyfiles: ^1.3.6
  npm-run-all2: ^8.0.4
  oxlint: ^1.28.0
  remove-glob: ^0.4.4
  rxjs: ^7.8.2
  sass: ^1.93.3
  sortablejs: ^1.15.6
  tslib: ^2.8.1
  typescript: ^5.8.3
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.6
  vue: ^3.5.22

# add a few named catalog: for Lerna-Lite to test its own code with real projects
catalogs:
  # Can be referenced through "catalog:vite6" or "catalog:vite7"
  vite6:
    vite: ^6.4.1
  vite7:
    vite: ^7.1.12

onlyBuiltDependencies:
  - 'cypress'
