packages:
  - demos/**
  - frameworks/**
  - packages/**
  - examples/**

catalog:
  '@4tw/cypress-drag-drop': ^2.3.0
  '@faker-js/faker': ^9.7.0
  '@fnando/sparkline': '^0.3.10'
  '@formkit/tempo': ^0.1.2
  '@types/fnando__sparkline': ^0.3.7
  '@types/node': ^22.15.2
  '@types/sortablejs': ^1.15.8
  cross-env: ^7.0.3
  cypress: ^14.3.2
  cypress-real-events: ^1.14.0
  dequal: ^2.0.3
  dompurify: ^3.2.5
  multiple-select-vanilla: ^3.5.0
  npm-run-all2: ^7.0.2
  rxjs: ^7.8.2
  sass: ^1.87.0
  sortablejs: ^1.15.6
  typescript: ^5.8.3
  vite: ^6.3.3
  whatwg-fetch: ^3.6.20
