packages:
  - demos/**
  - frameworks/**
  - frameworks-plugins/**
  - packages/**
  - '!**/dist/**'

minimumReleaseAge: 2880 # 2 days in minutes
minimumReleaseAgeExclude:
  # exclude packages that I personally maintain and are safe to use on the same day
  - '@lerna-lite/*'

catalog:
  '@4tw/cypress-drag-drop': ^2.3.1
  '@angular-eslint/eslint-plugin': ^21.3.1
  '@faker-js/faker': ^10.4.0
  '@fnando/sparkline': ^0.3.10
  '@formkit/tempo': ^1.0.0
  '@popperjs/core': ^2.11.8
  '@types/fnando__sparkline': ^0.3.7
  '@types/node': ^24.12.2
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@types/sortablejs': ^1.15.9
  '@vitejs/plugin-react': ^6.0.1
  '@vitejs/plugin-vue': ^6.0.6
  '@vitest/coverage-v8': ^5.0.0-beta.1
  '@vitest/ui': ^5.0.0-beta.1
  bootstrap: ^5.3.8
  cross-env: ^10.1.0
  cypress: ^15.14.2
  cypress-real-events: ^1.15.0
  dequal: ^2.0.3
  dompurify: ^3.4.1
  globals: ^17.5.0
  i18next: ^25.10.10
  i18next-vue: ^5.4.0
  jsdom: ^29.1.1
  jsdom-global: ^3.0.2
  jspdf: ^4.2.1
  multiple-select-vanilla: ^5.1.0
  native-copyfiles: ^2.0.1
  npm-run-all2: ^8.0.4
  oxlint: 1.43.0
  react: ^19.2.5
  react-dom: ^19.2.5
  react-router: ^7.14.2
  remove-glob: ^1.2.0
  rxjs: ^7.8.2
  sass: ^1.99.0
  sortablejs: ^1.15.7
  tslib: ^2.8.1
  typescript: ^6.0.3
  vite: ^8.0.10
  vitest: ^5.0.0-beta.1
  vue: ^3.5.33

overrides:
  '@hono/node-server': ^1.19.14
  '@isaacs/brace-expansion': ^5.0.1
  hono: ^4.12.16
  lodash: ^4.18.1
  minimatch: ^10.2.5
  picomatch: ^4.0.4
