import { type Routes } from '@angular/router';

export const routes: Routes = [
  { path: 'home', loadComponent: () => import('./examples/home.component').then((m) => m.HomeComponent) },
  { path: 'example01', loadComponent: () => import('./examples/example01.component').then((m) => m.Example1Component) },
  { path: 'example02', loadComponent: () => import('./examples/example02.component').then((m) => m.Example2Component) },
  { path: 'example03', loadComponent: () => import('./examples/example03.component').then((m) => m.Example3Component) },
  { path: 'example04', loadComponent: () => import('./examples/example04.component').then((m) => m.Example4Component) },
  { path: 'example05', loadComponent: () => import('./examples/example05.component').then((m) => m.Example5Component) },
  { path: 'example06', loadComponent: () => import('./examples/example06.component').then((m) => m.Example6Component) },
  { path: 'example07', loadComponent: () => import('./examples/example07.component').then((m) => m.Example7Component) },
  { path: 'example08', loadComponent: () => import('./examples/example08.component').then((m) => m.Example8Component) },
  { path: 'example09', loadComponent: () => import('./examples/example09.component').then((m) => m.Example9Component) },
  { path: 'example10', loadComponent: () => import('./examples/example10.component').then((m) => m.Example10Component) },
  { path: 'example11', loadComponent: () => import('./examples/example11.component').then((m) => m.Example11Component) },
  { path: 'example12', loadComponent: () => import('./examples/example12.component').then((m) => m.Example12Component) },
  { path: 'example13', loadComponent: () => import('./examples/example13.component').then((m) => m.Example13Component) },
  { path: 'example14', loadComponent: () => import('./examples/example14.component').then((m) => m.Example14Component) },
  { path: 'example15', loadComponent: () => import('./examples/example15.component').then((m) => m.Example15Component) },
  { path: 'example16', loadComponent: () => import('./examples/example16.component').then((m) => m.Example16Component) },
  { path: 'example17', loadComponent: () => import('./examples/example17.component').then((m) => m.Example17Component) },
  { path: 'example18', loadComponent: () => import('./examples/example18.component').then((m) => m.Example18Component) },
  { path: 'example19', loadComponent: () => import('./examples/example19.component').then((m) => m.Example19Component) },
  { path: 'example20', loadComponent: () => import('./examples/example20.component').then((m) => m.Example20Component) },
  { path: 'example21', loadComponent: () => import('./examples/example21.component').then((m) => m.Example21Component) },
  { path: 'example22', loadComponent: () => import('./examples/example22.component').then((m) => m.Example22Component) },
  { path: 'example23', loadComponent: () => import('./examples/example23.component').then((m) => m.Example23Component) },
  { path: 'example24', loadComponent: () => import('./examples/example24.component').then((m) => m.Example24Component) },
  { path: 'example25', loadComponent: () => import('./examples/example25.component').then((m) => m.Example25Component) },
  { path: 'example26', loadComponent: () => import('./examples/example26.component').then((m) => m.Example26Component) },
  { path: 'example27', loadComponent: () => import('./examples/example27.component').then((m) => m.Example27Component) },
  { path: 'example28', loadComponent: () => import('./examples/example28.component').then((m) => m.Example28Component) },
  { path: 'example29', loadComponent: () => import('./examples/example29.component').then((m) => m.Example29Component) },
  { path: 'example30', loadComponent: () => import('./examples/example30.component').then((m) => m.Example30Component) },
  { path: 'example31', loadComponent: () => import('./examples/swt-common-grid-test.component').then((m) => m.SwtCommonGridTestComponent) },
  { path: 'example32', loadComponent: () => import('./examples/example32.component').then((m) => m.Example32Component) },
  { path: 'example33', loadComponent: () => import('./examples/example33.component').then((m) => m.Example33Component) },
  { path: 'example34', loadComponent: () => import('./examples/example34.component').then((m) => m.Example34Component) },
  { path: 'example35', loadComponent: () => import('./examples/example35.component').then((m) => m.Example35Component) },
  { path: 'example36', loadComponent: () => import('./examples/example36.component').then((m) => m.Example36Component) },
  { path: 'example37', loadComponent: () => import('./examples/example37.component').then((m) => m.Example37Component) },
  { path: 'example38', loadComponent: () => import('./examples/example38.component').then((m) => m.Example38Component) },
  { path: 'example39', loadComponent: () => import('./examples/example39.component').then((m) => m.Example39Component) },
  { path: 'example40', loadComponent: () => import('./examples/example40.component').then((m) => m.Example40Component) },
  { path: 'example41', loadComponent: () => import('./examples/example41.component').then((m) => m.Example41Component) },
  { path: 'example42', loadComponent: () => import('./examples/example42.component').then((m) => m.Example42Component) },
  { path: 'example43', loadComponent: () => import('./examples/example43.component').then((m) => m.Example43Component) },
  { path: 'example44', loadComponent: () => import('./examples/example44.component').then((m) => m.Example44Component) },
  { path: 'example45', loadComponent: () => import('./examples/example45.component').then((m) => m.Example45Component) },
  { path: 'example46', loadComponent: () => import('./examples/example46.component').then((m) => m.Example46Component) },
  { path: 'example47', loadComponent: () => import('./examples/example47.component').then((m) => m.Example47Component) },
  { path: 'example48', loadComponent: () => import('./examples/example48.component').then((m) => m.Example48Component) },
  { path: 'example49', loadComponent: () => import('./examples/example49.component').then((m) => m.Example49Component) },
  { path: 'example50', loadComponent: () => import('./examples/example50.component').then((m) => m.Example50Component) },
  { path: '', redirectTo: '/example34', pathMatch: 'full' },
  { path: '**', redirectTo: '/example34', pathMatch: 'full' },
];
