name: Cypress E2E Test Results

on:
  workflow_run:
    workflows: ["E2E Tests (Cypress)"]
    types:
      - completed
permissions: {}

jobs:
  test-results:
    name: E2E Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write

      # needed unless run with comment_mode: off
      pull-requests: write

      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@2a4aebd3cbaad4fd177bb9819f3553fa8e2b8cd0
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Publish Cypress E2E Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          check_name: Cypress E2E Test Results
          files: "artifacts/**/*.json"
