name: Framework Tests - React

on:
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '!.github/workflows/ci.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        node: [22]
        platform:
          - ubuntu-latest

    name: '${{matrix.platform}} / Node ${{ matrix.node }}'
    runs-on: ${{matrix.platform}}
    if: ${{ !startsWith(github.event.head_commit.message, 'docs:') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: true

      - run: pnpm --version

      - name: Build Slickgrid-Universal packages
        run: pnpm build:universal

      - name: Slickgrid-React Framework Build
        run: pnpm react:build:framework

      - name: Website Dev Build (served for Cypress)
        run: pnpm react:build:demo

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Ensure Cypress binary is installed
        run: pnpm exec cypress install

      - name: Start HTTP Server
        run: pnpm react:serve &

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: demos/react
          wait-on: 'http://localhost:8000'
          config-file: test/cypress.config.ts
          browser: chrome
          record: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          Cypress_extended: true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: test/cypress/screenshots
